<div class="card border-0 shadow-none">
    <!-- Unified Header -->
    <div class="card-header border-0 pb-3" style="background-color: var(--theme-color-1) !important; color: white !important; border-radius: 8px 8px 0 0;">
        <div class="row align-items-center">
            <div class="col-md-6 mb-2 mb-md-0">
                <small class="d-block opacity-75 text-uppercase fw-bold" style="font-size: 0.65rem; letter-spacing: 1px;">KODE GENERATE</small>
                <h5 class="mb-0 text-white fw-bold">{{ $history->kode_generate ?? 'BATCH-' . $history->id }}</h5>
            </div>
            <div class="col-md-3 mb-2 mb-md-0 border-start border-white border-opacity-10 ps-md-4">
                <small class="d-block opacity-75 text-uppercase fw-bold" style="font-size: 0.65rem; letter-spacing: 1px;">PERIODE</small>
                <h6 class="mb-0 text-white fw-bold">{{ config('global.nama_bulan')[(int)$history->bulan] }} {{ $history->tahun }}</h6>
            </div>
            <div class="col-md-3 text-md-end border-start border-white border-opacity-10 ps-md-4">
                <small class="d-block opacity-75 text-uppercase fw-bold" style="font-size: 0.65rem; letter-spacing: 1px;">GENERATED BY</small>
                <h6 class="mb-0 text-white fw-bold">{{ $history->user->name }}</h6>
                <small class="d-block opacity-50" style="font-size: 0.6rem;">{{ date('d M Y H:i', strtotime($history->created_at)) }}</small>
            </div>
        </div>
    </div>

    <!-- Unified Table -->
    <div class="table-responsive" style="max-height: 500px; overflow-y: auto;">
        <table class="table mb-0 text-nowrap align-middle">
            <thead class="sticky-top" style="background-color: var(--theme-color-1) !important; color: white !important; top: -1px; z-index: 10;">
                <tr>
                    <th class="text-white border-0 py-2 ps-4" style="font-size: 0.7rem; letter-spacing: 0.5px;">NIK</th>
                    <th class="text-white border-0 py-2" style="font-size: 0.7rem; letter-spacing: 0.5px;">NAMA KARYAWAN</th>
                    <th class="text-white border-0 py-2" style="font-size: 0.7rem; letter-spacing: 0.5px;">NO. PINJAMAN</th>
                    <th class="text-white border-0 py-2 text-center" style="font-size: 0.7rem; letter-spacing: 0.5px;">CICILAN KE</th>
                    <th class="text-white border-0 py-2 text-end pe-4" style="font-size: 0.7rem; letter-spacing: 0.5px;">NOMINAL</th>
                </tr>
            </thead>
            <tbody class="table-border-bottom-0">
                @php $total = 0; @endphp
                @foreach ($history->pembayaran_pinjaman as $pay)
                    @php $total += $pay->jumlah_bayar; @endphp
                    <tr>
                        <td class="py-2 ps-4">
                            <span class="text-body fw-bold" style="font-size: 0.8rem;">{{ $pay->pinjaman->nik }}</span>
                        </td>
                        <td class="py-2">
                            <div class="d-flex align-items-center">
                                <span class="fw-bold text-dark me-2" style="font-size: 0.8rem;">{{ $pay->pinjaman->karyawan->nama_karyawan }}</span>
                                <small class="text-muted opacity-75" style="font-size: 0.7rem;">• {{ $pay->pinjaman->karyawan->jabatan->nama_jabatan ?? '-' }}</small>
                            </div>
                        </td>
                        <td class="py-2">
                            <span class="badge bg-label-secondary border-0 bg-opacity-10 text-dark" style="font-size: 0.7rem;">{{ $pay->pinjaman->no_pinjaman }}</span>
                        </td>
                        <td class="py-2 text-center">
                            <span class="badge bg-label-info px-2 py-1" style="font-size: 0.7rem;">
                                <i class="ti ti-hash ti-xxs me-1"></i> {{ $pay->rencana_cicilan ? $pay->rencana_cicilan->cicilan_ke : '-' }}
                            </span>
                        </td>
                        <td class="py-2 text-end pe-4">
                            <span class="fw-bold text-success" style="font-size: 0.85rem;">Rp{{ number_format($pay->jumlah_bayar, 0, ',', '.') }}</span>
                        </td>
                    </tr>
                @endforeach
            </tbody>
            <tfoot class="sticky-bottom" style="background-color: var(--theme-color-1) !important; color: white !important; bottom: -1px; z-index: 10;">
                <tr>
                    <th colspan="4" class="text-end py-2 ps-4 border-0">
                        <span class="text-white opacity-75 fw-bold text-uppercase" style="font-size: 0.7rem; letter-spacing: 1px;">Total Batch Pembayaran</span>
                    </th>
                    <th class="text-end py-2 pe-4 border-0">
                        <h6 class="mb-0 fw-bold text-white">Rp{{ number_format($total, 0, ',', '.') }}</h6>
                    </th>
                </tr>
            </tfoot>
        </table>
    </div>

    <!-- Modal Footer as part of card -->
    <div class="card-footer border-0 bg-transparent text-end pt-3 pb-3">
        <button type="button" class="btn btn-label-secondary btn-sm px-4" data-bs-dismiss="modal">
            <i class="ti ti-x me-1 ti-xs"></i> Tutup Detail
        </button>
    </div>
</div>
